#include "Augment.h"

extern const AugDef ALL_AUGS[] = {
    // ── 일반 ───────────────────────────────────────────
    { AugType::DMG_UP,        AugRarity::COMMON,    AugUnique::NONE, "DMG+5",
      { L"공격력 증가", L"Attack Up", L"攻撃力アップ" },
      { L"공격력 +9  (고정 가산)", L"Attack +9  (flat)", L"攻撃力 +9  (固定)" },
      L"ATK +9  (가산)" },
    { AugType::RATE_UP,       AugRarity::COMMON,    AugUnique::NONE, "RATE+4%",
      { L"연사 속도 증가", L"Fire Rate Up", L"連射速度アップ" },
      { L"연사 속도 +4%  (백분율 누적)", L"Fire rate +4%  (percent)", L"連射速度 +4%  (%累積)" },
      L"연사 +4%" },
    { AugType::SPD_UP,        AugRarity::COMMON,    AugUnique::NONE, "BSPD+30",
      { L"탄속 증가", L"Bullet Speed Up", L"弾速アップ" },
      { L"탄환 속도 +30", L"Bullet speed +30", L"弾速 +30" },
      L"탄속 +30" },
    { AugType::MOVE_UP,       AugRarity::COMMON,    AugUnique::NONE, "MOVE+5%",
      { L"이동속도 증가", L"Move Speed Up", L"移動速度アップ" },
      { L"이동 속도 +5%", L"Move speed +5%", L"移動速度 +5%" },
      L"이동 +5%" },
    { AugType::VISION_UP,     AugRarity::COMMON,    AugUnique::NONE, "VISION+70",
      { L"시야 증가", L"Vision Up", L"視界アップ" },
      { L"시야(필드 크기) +70  ·  최대 5중첩 (+350)",
        L"View (field) +70  ·  max 5 stacks (+350)",
        L"視界(フィールド) +70  ·  最大5重 (+350)" },
      L"시야 +70  ·  최대 5중첩" },
    { AugType::REGEN_UP,      AugRarity::COMMON,    AugUnique::NONE, "REGEN",
      { L"체력 재생", L"Regeneration", L"体力リジェネ" },
      { L"약 3.5초마다 체력 1 추가 회복  (중첩 가능)",
        L"Heal ~1 HP every 3.5s  (stackable)",
        L"約3.5秒ごとに体力1回復  (重複可)" },
      L"재생 +0.28/s" },

    // ── 희귀 ───────────────────────────────────────────
    { AugType::GLASS_CANNON,  AugRarity::RARE,      AugUnique::NONE, "GLASSCANNON",
      { L"유리대포", L"Glass Cannon", L"ガラスの大砲" },
      { L"공격력 +50%  ·  최대 체력 -35%", L"Attack +50%  ·  Max HP -35%", L"攻撃力 +50%  ·  最大体力 -35%" },
      L"ATK +50%  ·  Max HP -35%" },
    { AugType::LIGHT_AMMO,    AugRarity::RARE,      AugUnique::NONE, "LIGHTAMMO",
      { L"가벼운 탄환", L"Light Ammo", L"軽量弾" },
      { L"연사 +15%  ·  탄속 +35%  ·  공격력 -12%",
        L"Fire rate +15%  ·  speed +35%  ·  Attack -12%",
        L"連射 +15%  ·  弾速 +35%  ·  攻撃力 -12%" },
      L"연사 +15%  ·  탄속 +35%  ·  ATK -12%" },
    { AugType::LIGHT_STEP,    AugRarity::RARE,      AugUnique::NONE, "LIGHTSTEP",
      { L"가벼운 발걸음", L"Light Step", L"軽い足取り" },
      { L"이동 속도 +30%  ·  피격 시 10초간 이 효과 정지",
        L"Move speed +30%  ·  disabled 10s when hit",
        L"移動速度 +30%  ·  被弾時10秒間 無効" },
      L"이동 +30%  ·  피격 10초 해제" },
    { AugType::RESERVED_AUG_037, AugRarity::RARE, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::BULLET_RAIN,   AugRarity::RARE,      AugUnique::NONE, "BULLETRAIN",
      { L"탄환 세례", L"Bullet Rain", L"弾幕の雨" },
      { L"15초마다 유도탄 20발 일제 발사  ·  발당 데미지 50%",
        L"Every 15s fire 20 homing shots  ·  50% dmg each",
        L"15秒ごとに誘導弾20発  ·  1発50%ダメージ" },
      L"유도탄 ×20발  ·  쿨 15초" },
    { AugType::CRIT,          AugRarity::RARE,      AugUnique::NONE, "CRIT",
      { L"치명타", L"Critical Strike", L"クリティカル" },
      { L"15% 확률로 치명타 (피해 ×2.0)  (중첩 시 확률 +15%, 최대 75%)",
        L"15% chance to crit (×2.0 dmg)  (stacks +15%, max 75%)",
        L"15%でクリティカル (×2.0)  (重複で+15%, 最大75%)" },
      L"크리 +15%  ·  배율 ×2.0" },
    { AugType::LIFESTEAL,     AugRarity::RARE,      AugUnique::NONE, "LIFESTEAL",
      { L"흡혈탄", L"Lifesteal", L"吸血弾" },
      { L"처치당 HP +0.08  (최대 4중첩 · 합 0.32/kill)",
        L"Heal +0.08/kill  (max 4 stacks · 0.32 total)",
        L"撃破毎 +0.08  (最大4重 · 合計0.32)" },
      L"처치당 HP +0.08  (4중첩)" },
    { AugType::BERSERK,       AugRarity::RARE,      AugUnique::NONE, "BERSERK",
      { L"광전사", L"Berserker", L"バーサーカー" },
      { L"체력이 낮을수록 공격력 증가  (최대 +60% · 빈사 시)",
        L"Lower HP = more attack  (up to +60% near death)",
        L"低HPほど攻撃力上昇  (瀕死時 最大+60%)" },
      L"저체력 시 ATK 최대 +60%" },
    { AugType::OVERDRIVE,     AugRarity::RARE,      AugUnique::NONE, "OVERDRIVE",
      { L"오버드라이브", L"Overdrive", L"オーバードライブ" },
      { L"공격력 +14  (고정 가산)", L"Attack +14  (flat)", L"攻撃力 +14  (固定)" },
      L"ATK +14  (가산)" },

    // ── 에픽 ───────────────────────────────────────────
    { AugType::CORE_OVERLOAD, AugRarity::EPIC,      AugUnique::NONE, "CORE_OVERLOAD",
      { L"코어 과부하", L"Core Overload", L"コア過負荷" },
      { L"공격력 +24  (고정 가산)", L"Attack +24  (flat)", L"攻撃力 +24  (固定)" },
      L"ATK +24  (가산)" },
    { AugType::VAMPIRE,       AugRarity::EPIC,      AugUnique::NONE, "VAMPIRE",
      { L"흡혈마", L"Vampire", L"吸血鬼" },
      { L"흡혈 한도 0.60 · Max HP +20 · 10킬마다 HP +1",
        L"Lifesteal cap 0.60 · Max HP +20 · +1 HP per 10 kills",
        L"吸血上限0.60 · 最大HP+20 · 10キル毎HP+1" },
      L"흡혈 상한 0.60  ·  Max HP +20" },
    { AugType::RESERVED_AUG_003, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_001, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::MINIATURIZE,   AugRarity::EPIC,      AugUnique::SIZE, "MINI",
      { L"축소화", L"Miniaturize", L"小型化" },
      { L"최대 체력 1/2  ·  보유 증강당 공격력 +6·연사 +1%  ·  이속 +20%  ·  크기 -20%",
        L"Max HP halved  ·  per aug: ATK +6·rate +1%  ·  move +20%  ·  size -20%",
        L"最大体力1/2  ·  強化1つ毎 攻撃+6・連射+1%  ·  移動+20%  ·  サイズ-20%" },
      L"Max HP 1/2  ·  증강당 ATK +6" },
    { AugType::GIGANTIFY,     AugRarity::EPIC,      AugUnique::SIZE, "GIGA",
      { L"거대화", L"Gigantify", L"巨大化" },
      { L"최대 체력 ×2  ·  초당 체력 약 1.2 회복  ·  이속 -32%  ·  크기 +45%",
        L"Max HP ×2  ·  ~1.2 HP/s regen  ·  move -32%  ·  size +45%",
        L"最大体力 ×2  ·  毎秒 約1.2回復  ·  移動 -32%  ·  サイズ +45%" },
      L"Max HP ×2  ·  재생 ~1.2/s  ·  이동 -32%" },
    { AugType::PIERCE,        AugRarity::EPIC,      AugUnique::NONE, "PIERCE",
      { L"관통", L"Pierce", L"貫通" },
      { L"명중 시 30% 확률로 적·장애물 관통",
        L"30% chance to pierce on hit",
        L"命中時30%で敵・障害物を貫通" },
      L"관통 확률 +30%" },
    { AugType::TWIN,          AugRarity::EPIC,      AugUnique::NONE, "TWIN",
      { L"더블", L"Twin", L"ダブル" },
      { L"한 번에 2발 발사  ·  공격력 -40%", L"Fire 2 shots at once  ·  Attack -40%", L"一度に2発発射  ·  攻撃力 -40%" },
      L"발사 ×2  ·  ATK -40%" },
    { AugType::CHAKRAM,       AugRarity::EPIC,      AugUnique::NONE, "CHAKRAM",
      { L"차크람", L"Chakram", L"チャクラム" },
      { L"넓게 공전하는 차크람 1개  ·  닿은 잡몹·일반 적 즉사, 원거리 적 큰 피해·적탄 막기  ·  파괴 시 6초 후 재생성",
        L"1 wide-orbiting chakram  ·  instakills large mobs, big dmg to gunners, blocks bullets  ·  respawns 6s",
        L"広く公転するチャクラム1個  ·  雑魚・自爆兵即死, 遠距離に大ダメージ・敵弾を防ぐ  ·  破壊後6秒で再生成" },
      L"차크람 ×1  ·  6초 재생성" },
    { AugType::BULLET_RAIN_2, AugRarity::EPIC,      AugUnique::NONE, "BULLETRAIN II",
      { L"탄환 세례 II", L"Bullet Rain II", L"弾幕の雨 II" },
      { L"탄환 세례 쿨다운 15초 → 10초  (요구: 탄환 세례)",
        L"Bullet Rain cooldown 15s → 10s  (req: Bullet Rain)",
        L"弾幕の雨 クールダウン 15秒 → 10秒  (要: 弾幕の雨)" },
      L"세례 쿨 15초 → 10초" },
    { AugType::CHAKRAM_2,     AugRarity::EPIC,      AugUnique::NONE, "CHAKRAM II",
      { L"차크람 II", L"Chakram II", L"チャクラム II" },
      { L"차크람 1개 → 2개  (요구: 차크람)", L"1 → 2 chakrams  (req: Chakram)", L"1個 → 2個  (要: チャクラム)" },
      L"차크람 1 → 2" },
    { AugType::DRONE,         AugRarity::EPIC,      AugUnique::NONE, "DRONE",
      { L"드론", L"Drone", L"ドローン" },
      { L"자동 조준 드론 1기 소환  ·  연사·탄속 50%",
        L"Summon 1 auto-aim drone  ·  50% fire rate·speed",
        L"自動照準ドローン1機  ·  連射・弾速50%" },
      L"드론 ×1  ·  화력 50%" },
    { AugType::LASER,         AugRarity::EPIC,      AugUnique::NONE, "LASER",
      { L"스캔 레이저", L"Scan Laser", L"スキャンレーザー" },
      { L"0.85초마다 조준 방향으로 중거리 관통 레이저 — 직선상 적 일소 (군중 제어)",
        L"Every 0.85s, a mid-range piercing laser along your aim — clears enemies in a line",
        L"0.85秒毎に照準方向へ中距離貫通レーザー — 直線上の敵を一掃 (群衆制御)" },
      L"0.85초 관통 빔  ·  사거리 560" },
    { AugType::RESERVED_AUG_050, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::LASER_2,       AugRarity::LEGENDARY, AugUnique::NONE, "LASER II",
      { L"스캔 레이저 II", L"Scan Laser II", L"スキャンレーザー II" },
      { L"레이저 발사 0.85→0.55초 · 사거리 560→760  (요구: 스캔 레이저)",
        L"Laser interval 0.85→0.55s · range 560→760  (req: Scan Laser)",
        L"レーザー 0.85→0.55秒・射程 560→760  (要: スキャンレーザー)" },
      L"간격 0.85→0.55초  ·  사거리 +200" },
    { AugType::PIERCE_2,      AugRarity::LEGENDARY, AugUnique::NONE, "PIERCE II",
      { L"관통 II", L"Pierce II", L"貫通 II" },
      { L"관통 확률 +30%  (요구: 관통)", L"Pierce chance +30%  (req: Pierce)", L"貫通確率 +30%  (要: 貫通)" },
      L"관통 +30%p" },
    { AugType::TWIN_2,        AugRarity::LEGENDARY, AugUnique::NONE, "TRIPLE",
      { L"트리플 샷", L"Triple Shot", L"トリプルショット" },
      { L"한 번에 2발 → 3발 · 공격력 -12%  (요구: 더블)", L"2 → 3 shots at once · Attack -12%  (req: Twin)", L"一度に2発 → 3発 · 攻撃-12%  (要: ダブル)" },
      L"발사 2→3  ·  ATK -12%" },
    { AugType::RESERVED_AUG_042, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_002, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_049, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_046, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_043, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::HACK_RANGED,   AugRarity::EPIC,      AugUnique::NONE, "HACK_RANGED",
      { L"해킹: 원거리", L"Hack: Ranged", L"ハック: 遠距離" },
      { L"원거리 몹 처치 시 20% 확률로 유도탄 5발  (적에게만 피해)",
        L"On ranged-mob kill, 20% chance: 5 homing shots  (enemy-only dmg)",
        L"遠距離敵撃破時20%で誘導弾5発  (敵のみ)" },
      L"원거리 처치 20%  ·  유도탄 ×5" },
    { AugType::PROB_CHAIN,    AugRarity::EPIC,      AugUnique::NONE, "PROBCHAIN",
      { L"확률적 연쇄 작용", L"Chance Ricochet", L"確率的連鎖" },
      { L"명중 시 30% 확률로 가까운 적에게 튕김  (최대 3회 · 뮤탈 글레이브)",
        L"On hit, 30% chance to ricochet to nearest enemy  (up to 3x)",
        L"命中時30%で近い敵に跳弾  (最大3回)" },
      L"명중 30%  ·  3회 튕김" },
    { AugType::DEATH_BLAST,   AugRarity::LEGENDARY, AugUnique::NONE, "DEATHBLAST",
      { L"연쇄 폭발", L"Death Blast", L"連鎖爆発" },
      { L"적 처치 시 폭발 — 주변 적에게 공격력 30% 피해 (폭발로 죽은 적은 추가 폭발 X)",
        L"On kill, explode — 30% ATK dmg nearby (blast-killed don't re-explode)",
        L"撃破時に爆発 — 周囲に攻撃力30%ダメージ (爆死は再爆発しない)" },
      L"처치 시 ATK 30% 폭발" },
    { AugType::SKILL_CLOSE,   AugRarity::EPIC,      AugUnique::NONE, "SKILL_CLOSE",
      { L"[스킬] 창 닫기", L"[Skill] Close Window", L"[スキル] ウィンドウを閉じる" },
      { L"액티브 스킬 획득 — 플레이어 중심 대폭발(넉백+피해)  (쿨 16초)",
        L"Active skill — explosion at the player (knockback+dmg)  (16s CD)",
        L"アクティブスキル — 自分中心の大爆発(ノックバック+ダメージ)  (CD16秒)" },
      L"쿨 16초  ·  폭발 넉백" },
    { AugType::SKILL_OVERCLOCK,AugRarity::EPIC,     AugUnique::NONE, "SKILL_OVCLK",
      { L"[스킬] 초집중", L"[Skill] Hyper Focus", L"[スキル] 超集中" },
      { L"액티브 — 5초간 시야 +50% · 적 행동 -30% · 대시 쿨 2초  (쿨 20초)",
        L"Active — 5s: vision +50%, enemies -30% speed, dash CD 2s  (20s CD)",
        L"アクティブ — 5秒: 視界+50%・敵-30%・ダッシュCD2秒  (CD20秒)" },
      L"쿨 20초  ·  5초 집중 모드" },

    // ── 전설 ───────────────────────────────────────────
    { AugType::POWER_SURGE,   AugRarity::LEGENDARY, AugUnique::NONE, "POWER_SURGE",
      { L"전력 증폭", L"Power Surge", L"パワーサージ" },
      { L"공격력 ×1.05  (3스택까지 · 이후 ×1.03 · 중첩)",
        L"Attack ×1.05  (stacks to 3 · then ×1.03)",
        L"攻撃力 ×1.05  (3まで · 以降 ×1.03)" },
      L"ATK ×1.05  (3중첩)" },
    { AugType::RANDOM_AUG,    AugRarity::LEGENDARY, AugUnique::NONE, "RANDOM",
      { L"랜덤 증강", L"Random Augment", L"ランダム強化" },
      { L"등급 무관 랜덤 버프 3개 즉시 획득  (디버프 없음)",
        L"Instantly gain 3 random buffs (any rarity, no debuff)",
        L"等級無関係のバフ3個を即獲得  (デバフ無し)" },
      L"랜덤 버프 ×3 즉시 획득" },
    { AugType::RESERVED_AUG_059, AugRarity::LEGENDARY, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::MK2,           AugRarity::LEGENDARY, AugUnique::NONE, "MK2",
      { L"MK2 내장", L"MK2 Core", L"MK2 内蔵" },
      { L"사망 시 공격력 비례 대폭발 + 풀 HP 부활  (1회, 페널티 없음)",
        L"On death: ATK-scaled blast + full-HP revive  (once, no penalty)",
        L"死亡時 攻撃力比例の大爆発+全回復で復活  (1回・ペナルティ無)" },
      L"사망 시 1회 부활  ·  대폭발" },
    { AugType::RESERVED_AUG_038, AugRarity::LEGENDARY, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::CHAIN,         AugRarity::LEGENDARY, AugUnique::NONE, "CHAIN",
      { L"연쇄 작용", L"Chain Reaction", L"連鎖反応" },
      { L"모든 총알이 무조건 2회 튕김  ·  총알 공격력 -30%",
        L"All bullets always ricochet 2x  ·  bullet damage -30%",
        L"全弾が必ず2回跳弾  ·  弾ダメージ -30%" },
      L"전탄 2회 튕김  ·  ATK -30%" },
    { AugType::SKILL_TIMESTOP,AugRarity::LEGENDARY, AugUnique::NONE, "SKILL_TSTOP",
      { L"[스킬] 시간 정지", L"[Skill] Time Stop", L"[スキル] 時間停止" },
      { L"액티브 스킬 획득 — 1.5초간 적·적탄막 정지 (나는 계속 행동)  (쿨 28초)",
        L"Active skill — freeze enemies & enemy bullets 1.5s  (28s CD)",
        L"アクティブスキル — 1.5秒 敵と敵弾を停止  (CD28秒)" },
      L"쿨 28초  ·  1.5초 시간 정지" },
    { AugType::BULLET_RAIN_3, AugRarity::LEGENDARY, AugUnique::NONE, "BULLETRAIN III",
      { L"탄환 세례 III", L"Bullet Rain III", L"弾幕の雨 III" },
      { L"탄환 세례 쿨다운 10초 → 5초  (요구: 탄환 세례 II)",
        L"Bullet Rain cooldown 10s → 5s  (req: Bullet Rain II)",
        L"弾幕の雨 クールダウン 10秒 → 5秒  (要: 弾幕の雨 II)" },
      L"세례 쿨 10초 → 5초" },
    { AugType::DRONE_2,       AugRarity::LEGENDARY, AugUnique::NONE, "DRONE II",
      { L"드론 II", L"Drone II", L"ドローン II" },
      { L"드론 1기 → 2기  (요구: 드론)",
        L"1 → 2 drones  (req: Drone)",
        L"1機 → 2機  (要: ドローン)" },
      L"드론 1 → 2" },
    { AugType::CHAKRAM_3,     AugRarity::LEGENDARY, AugUnique::NONE, "CHAKRAM III",
      { L"차크람 III", L"Chakram III", L"チャクラム III" },
      { L"차크람 2개 → 3개  (요구: 차크람 II)", L"2 → 3 chakrams  (req: Chakram II)", L"2個 → 3個  (要: チャクラム II)" },
      L"차크람 2 → 3" },

    // ── 디버프 ─────────────────────────────────────────
    { AugType::D_RMOB_MAX,    AugRarity::DEBUFF,    AugUnique::NONE, "D_RMOBMAX",
      { L"원거리 몹 증원", L"Ranged Reinforce", L"遠距離増援" },
      { L"원거리 몹 최대 수 +1 · 스폰 0.5초 빨라짐 · 원거리 처치 EXP +12",
        L"Ranged max +1 · spawn 0.5s faster · ranged-kill EXP +12",
        L"遠距離敵の最大数+1・出現0.5秒短縮・撃破EXP +12" },
      L"원거리몹 최대 +1  ·  EXP +12" },
    { AugType::D_RMOB_HP,     AugRarity::DEBUFF,    AugUnique::NONE, "D_RMOBPOW",
      { L"원거리 몹 강화", L"Ranged Empower", L"遠距離強化" },
      { L"원거리 몹 체력·공격력 +20% · 원거리 처치 EXP +6",
        L"Ranged HP·ATK +20% · ranged-kill EXP +6",
        L"遠距離敵の体力・攻撃+20%・撃破EXP +6" },
      L"원거리몹 HP·ATK +20%  ·  EXP +6" },
    { AugType::D_RMOB_DELAY,  AugRarity::DEBUFF,    AugUnique::NONE, "D_RMOBDELAY",
      { L"원거리 몹 가속", L"Ranged Haste", L"遠距離加速" },
      { L"원거리 몹 이동 속도 +20% · 원거리 처치 EXP +5",
        L"Ranged move speed +20% · ranged-kill EXP +5",
        L"遠距離敵の移動+20%・撃破EXP +5" },
      L"원거리몹 이동 +20%  ·  EXP +5" },
    { AugType::D_MOB_SPAWN,   AugRarity::DEBUFF,    AugUnique::NONE, "D_MOBSPAWN",
      { L"로터 폭주", L"Rotor Surge", L"ローター暴走" },
      { L"로터 생성 빈도 증가 · 동시 한도 +12 · 처치 EXP +1",
        L"Rotor spawn frequency increased · cap +12 · kill EXP +1",
        L"ローター出現頻度増加・同時上限+12・撃破EXP +1" },
      L"생성 빈도 ↑  ·  EXP +1" },
    { AugType::D_APPROACH,    AugRarity::DEBUFF,    AugUnique::NONE, "D_APPROACH",
      { L"다가오는 죽음", L"Approaching Death", L"Approaching Death" },
      { L"무적 붉은 오브가 추적 · 초당 EXP +0.5 · 최대 3회, 중복 시 속도 +20%",
        L"Invincible red orb chases you · EXP +0.5/s · max 3, +20% orb speed per stack",
        L"Invincible red orb chases you · EXP +0.5/s · max 3" },
      L"무적 오브 추적  ·  EXP +0.5/s" },
    { AugType::D_MOB_SPEED,   AugRarity::DEBUFF,    AugUnique::NONE, "D_MOBSPD",
      { L"로터 가속", L"Rotor Haste", L"ローター加速" },
      { L"로터 이동 속도 +10% · 초당 EXP +0.5",
        L"Rotor move speed +10% · EXP +0.5/s",
        L"ローター移動速度+10%・毎秒EXP +0.5" },
      L"로터 이동 +10%  ·  EXP +0.5/s" },
    { AugType::D_GLASS_HEART, AugRarity::DEBUFF,    AugUnique::NONE, "D_GLASS",
      { L"유리 심장", L"Glass Heart", L"Glass Heart" },
      { L"최대 체력 -20% · 전체 EXP +3%", L"Max HP -20% · all EXP +3%", L"Max HP -20% · all EXP +3%" },
      L"Max HP -20%  ·  전체EXP +3%" },
    { AugType::D_BULLET_STUCK,AugRarity::DEBUFF,    AugUnique::NONE, "D_STUCK",
      { L"탄 걸림", L"Jammed", L"Jammed" },
      { L"연사 속도 -10% · 전체 EXP +5%", L"Fire rate -10% · all EXP +5%", L"Fire rate -10% · all EXP +5%" },
      L"연사 -10%  ·  전체EXP +5%" },
    { AugType::RESERVED_AUG_023, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_017, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_018, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_019, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::D_MOB_HP,      AugRarity::DEBUFF,    AugUnique::NONE, "D_ROTORHP",
      { L"로터 체력 강화", L"Rotor HP Up", L"ローター体力強化" },
      { L"로터 체력 +30% · 로터 처치 EXP +2",
        L"Rotor HP +30% · rotor kill EXP +2",
        L"ローター体力+30%・ローター撃破EXP +2" },
      L"로터 HP +30%  ·  EXP +2" },
    { AugType::D_SLOW_MOVE,   AugRarity::DEBUFF,    AugUnique::NONE, "D_SLOWMV",
      { L"무거운 다리", L"Heavy Legs", L"Heavy Legs" },
      { L"플레이어 이동 속도 -5% · 전체 EXP +3%", L"Player move speed -5% · all EXP +3%", L"Player move speed -5% · all EXP +3%" },
      L"이동 -5%  ·  전체EXP +3%" },
    { AugType::RESERVED_AUG_031, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_016, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_026, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_030, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_029, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::D_BLEED,       AugRarity::DEBUFF,    AugUnique::NONE, "D_BLEED",
      { L"출혈", L"Bleed", L"Bleed" },
      { L"체력 회복 -1.0/s · 회복이 0이면 등장하지 않음 · 전체 EXP +12%",
        L"Regen -1.0/s · hidden at 0 regen · all EXP +12%",
        L"Regen -1.0/s · hidden at 0 regen · all EXP +12%" },
      L"재생 -1.0/s  ·  전체EXP +12%" },
    { AugType::D_WEAKEN,      AugRarity::DEBUFF,    AugUnique::NONE, "D_WEAKEN",
      { L"약화", L"Weaken", L"弱体化" },
      { L"공격력 -12% · 전체 EXP +10%", L"Attack -12% · all EXP +10%", L"攻撃力 -12%・全EXP +10%" },
      L"ATK -12%  ·  전체EXP +10%" },
    // ── 로터류(잡몹) 전용 디버프 (확장, 중첩 가능) ──
    { AugType::RESERVED_AUG_061, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"REMOVED", L"REMOVED", L"REMOVED" },
      { L"퇴역 증강 슬롯", L"Retired augment slot", L"退役した増強スロット" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_024, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_025, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::S_CHAOS,       AugRarity::SPECIAL,   AugUnique::NONE, "CHAOS",
      { L"대혼란", L"Chaos", L"大混乱" },
      { L"보유 증강을 모두 잊고 같은 개수만큼 무작위 재배열  (약 60% 버프 · 40% 디버프)",
        L"Forget all augments and randomly recompose the same count  (~60% buffs · 40% debuffs)",
        L"所持強化を全て忘れ、同数をランダムに再構成  (約60%バフ · 40%デバフ)" },
      L"—  (전체 재배분)" },
    { AugType::S_PANDORA,     AugRarity::SPECIAL,   AugUnique::NONE, "PANDORA",
      { L"판도라의 상자", L"Pandora's Box", L"パンドラの箱" },
      { L"버프 3개 + 디버프 2개 즉시 획득", L"Instantly gain 3 buffs + 2 debuffs", L"バフ3個 + デバフ2個を即獲得" },
      L"버프 +3  ·  디버프 +2" },

    // ── 조합 (COMBO) — 레시피 충족 시에만 카드로 등장 ───────
    { AugType::RESERVED_AUG_005, AugRarity::COMBO, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::CB_BLOODLORD,   AugRarity::COMBO,    AugUnique::NONE, "CB_BLOOD",
      { L"피의 군주", L"Bloodlord", L"血の君主" },
      { L"[조합] 최대 체력 +15 · 재생 +0.25/s",
        L"[Combo] Max HP +15 · regen +0.25/s",
        L"[組合] 最大HP+15・再生+0.25/s" },
      L"Max HP +15  ·  재생 +0.25/s" },
    { AugType::RESERVED_AUG_009, AugRarity::COMBO, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_011, AugRarity::COMBO, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_010, AugRarity::COMBO, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_006, AugRarity::COMBO, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::CB_WARLORD,     AugRarity::COMBO,    AugUnique::NONE, "CB_WAR",
      { L"전쟁군주", L"Warlord", L"戦争君主" },
      { L"[조합] 획득 즉시 공격력 +15% · 1000킬마다 공격력 +5%·연사 +2%·탄속 +2% (최대 7스택)",
        L"[Combo] On acquisition, ATK +15% · every 1000 kills: ATK +5%, fire rate +2%, bullet speed +2% (max 7 stacks)",
        L"[組合] 獲得時に攻撃+15% · 1000撃破毎に攻撃+5%・連射+2%・弾速+2% (最大7重)" },
      L"ATK +15% · 1000킬마다 ATK +5%·연사 +2%·탄속 +2% (최대 7)" },
    { AugType::RESERVED_AUG_013, AugRarity::COMBO, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_008, AugRarity::COMBO, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_007, AugRarity::COMBO, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::BULLET_RAIN_ETERNAL, AugRarity::MYTHIC, AugUnique::NONE, "RAIN_ETERNAL",
      { L"무한 세례", L"Endless Rain", L"無限の雨" },
      { L"쿨다운 4초 · 적 처치마다 쿨다운 0.2초 감소 (최소 3초)",
        L"Cooldown 4s · each kill cuts cooldown by 0.2s (min 3s)",
        L"クールダウン4秒 · 撃破毎にCD0.2秒短縮 (最短3秒)" },
      L"쿨 4초  ·  처치마다 -0.2초" },
    { AugType::DRONE_HIVE,    AugRarity::MYTHIC, AugUnique::NONE, "DRONE_HIVE",
      { L"군집 지능", L"Hive Mind", L"群知能" },
      { L"드론 4기 운용 · 각 드론 화력은 50% 유지",
        L"Run 4 drones · each drone keeps 50% output",
        L"ドローン4機運用 · 各ドローン火力50%維持" },
      L"드론 ×4  ·  각 화력 50%" },
    { AugType::LASER_CONVERGE, AugRarity::MYTHIC, AugUnique::NONE, "LASER_CONV",
      { L"수렴", L"Convergence", L"収束" },
      { L"스캔 레이저 0.26초 간격 · 사거리 700 · 빔 폭 +50% (직선 일소)",
        L"Scan laser every 0.26s · range 700 · beam width +50%",
        L"スキャンレーザー0.26秒間隔 · 射程700 · ビーム幅+50%" },
      L"레이저 0.26초  ·  사거리 700" },
    { AugType::PIERCE_RAILSLUG, AugRarity::MYTHIC, AugUnique::NONE, "PIERCE_RAIL",
      { L"철갑탄", L"Railslug", L"徹甲弾" },
      { L"관통 90% 고정 · 공격력 +25 (가산) · 탄속 +50% (멈추지 않는 탄)",
        L"90% pierce · attack +25 (flat) · bullet speed +50%",
        L"貫通90% · 攻撃+25(加算) · 弾速+50%" },
      L"관통 90%  ·  ATK +25  ·  탄속 +50%" },
    // Reserved augment metadata.
    { AugType::RESERVED_AUG_014, AugRarity::COMBO, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_028, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_033, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_021, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_015, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_027, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_022, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_034, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_020, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::LIFESTEAL_2,   AugRarity::EPIC,     AugUnique::NONE, "LIFESTEAL2",
      { L"흡혈탄 II", L"Lifesteal II", L"吸血弾 II" },
      { L"흡혈 한도 0.32→0.48 · 10킬마다 HP +1  (요구: 흡혈탄)",
        L"Lifesteal cap 0.32→0.48 · +1 HP per 10 kills  (req: Lifesteal)",
        L"吸収上限0.32→0.48 · 10キル毎HP+1  (要:吸収弾)" },
      L"흡혈 상한 0.32→0.48" },
    { AugType::CHAIN_2,       AugRarity::LEGENDARY, AugUnique::NONE, "CHAIN2",
      { L"연쇄 작용 II", L"Chain Reaction II", L"連鎖反応 II" },
      { L"튕김 2→3회 · 총알 -30%→-22%  (요구: 연쇄 작용)",
        L"Ricochet 2→3 · bullet dmg -30%→-22%  (req: Chain)",
        L"跳弾2→3 · 弾-30%→-22%  (要:連鎖反応)" },
      L"튕김 2→3  ·  ATK -22%" },
    { AugType::RESERVED_AUG_054, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_051, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_040, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::CHAKRAM_SINGULARITY, AugRarity::MYTHIC, AugUnique::NONE, "CHAK_SING",
      { L"특이점", L"Singularity", L"特異点" },
      { L"차크람이 적을 끌어당김 · 접촉 지속 피해  (요구: 차크람 III)",
        L"Chakrams pull enemies in · contact DOT  (req: Chakram III)",
        L"チャクラムが敵を吸引 · 接触DoT  (要:チャクラムIII)" },
      L"흡인 + DoT" },
    { AugType::RESERVED_AUG_055, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::SKILL_DASH_UP, AugRarity::EPIC,    AugUnique::NONE, "DASH_UP",
      { L"[스킬] 섬광 돌진", L"[Skill] Flash Dash", L"[スキル] 閃光突進" },
      { L"대시 시 유도탄 3~5발 · 이후 3발 ×2 공격력  (SHIFT · 대시 강화)",
        L"Dash — 3~5 homing shots · next 3 shots ×2 dmg  (SHIFT upgrade)",
        L"ダッシュ — 誘導弾3~5 · 次3発×2  (SHIFT強化)" },
      L"대시 시 유도탄  ·  이후 ×2" },
    { AugType::RESERVED_AUG_056, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RIFLE_STABILITY, AugRarity::EPIC,    AugUnique::NONE, "RIFLE_STAB",
      { L"정조준", L"Marksman", L"精密照準" },
      { L"[소총] 흩어짐 제거 · 공격력 +8",
        L"[Rifle] no spread · Attack +8",
        L"[ライフル] 拡散なし · 攻撃+8" },
      L"퍼짐 제거  ·  ATK +8" },
    { AugType::RESERVED_AUG_058, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::HP_UP,         AugRarity::COMMON,    AugUnique::NONE, "HP_UP",
      { L"체력 증가", L"HP Up", L"体力アップ" },
      { L"최대 체력 +15  (중첩 가능)",
        L"Max HP +15  (stackable)",
        L"最大体力 +15  (重複可)" },
      L"Max HP +15" },
    { AugType::FIREWALL,      AugRarity::RARE,      AugUnique::NONE, "FIREWALL",
      { L"방화벽", L"Firewall", L"ファイアウォール" },
      { L"받는 피해 -12%  (1회 획득)",
        L"Damage taken -12%  (once)",
        L"被ダメ -12%  (1回のみ)" },
      L"받는 피해 -12%" },
    { AugType::REGEN_2,       AugRarity::EPIC,      AugUnique::NONE, "REGEN2",
      { L"재생 II", L"Regen II", L"再生 II" },
      { L"재생 +0.45/s  ·  체력 40% 이하 시 재생 ×2  (요구: 재생 증강 권장)",
        L"Regen +0.45/s  ·  below 40% HP regen ×2  (works best with Regen Up)",
        L"再生 +0.45/s  ·  体力40%以下で再生×2" },
      L"재생 +0.45/s  ·  저체력 ×2" },
    { AugType::CB_BASTION,    AugRarity::COMBO,     AugUnique::NONE, "CB_BAST",
      { L"철벽", L"Bastion", L"鉄壁" },
      { L"[조합] 최대 체력 +20% · 재생 +0.45/s · 받는 피해 -10%p",
        L"[Combo] Max HP +20% · regen +0.45/s · damage taken -10%p",
        L"[組合] 最大HP+20% · 再生+0.45/s · 被ダメ-10%p" },
      L"Max HP +20%  ·  재생 +0.45  ·  피해 -10%" },
    { AugType::CB_LIFEBUOY,   AugRarity::COMBO,     AugUnique::NONE, "CB_LIFE",
      { L"구명줄", L"Lifebuoy", L"救命浮輪" },
      { L"[조합] 재생 +0.25/s · 이동 +12% · 10킬→7킬 회복 · 피격 정지 6초",
        L"[Combo] regen +0.25/s · move +12% · heal every 7 kills · hit lock 6s",
        L"[組合] 再生+0.25/s · 移動+12% · 7キル回復 · 被弾停止6秒" },
      L"재생 +0.25  ·  이동 +12%  ·  7킬 회복" },
    { AugType::RESERVED_AUG_044, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_045, AugRarity::MYTHIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::DEATH_BLAST_2, AugRarity::LEGENDARY, AugUnique::NONE, "DBLST2",
      { L"연쇄 폭발 II", L"Death Blast II", L"連鎖爆発 II" },
      { L"폭발 피해 30%→40% · 반경 +40%  (요구: 연쇄 폭발)",
        L"Blast dmg 30%→40% · radius +40%  (req: Death Blast)",
        L"爆発30%→40% · 範囲+40%  (要:連鎖爆発)" },
      L"폭발 30%→40%  ·  반경 +40%" },
    { AugType::RESERVED_AUG_012, AugRarity::COMBO, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_039, AugRarity::EPIC, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_052, AugRarity::LEGENDARY, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_041, AugRarity::LEGENDARY, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
    { AugType::RESERVED_AUG_032, AugRarity::DEBUFF, AugUnique::NONE, "REMOVED",
      { L"?? ? ??", L"Removed augment", L"?? ??? ??" },
      { L"?? ?? ?? ?? ? ? ?? ??.",
        L"This augment is retired from the current gameplay roster.",
        L"?? ??? ??? ??? ??? ??? ???" },
      L"REMOVED" },
};

static_assert(static_cast<int>(sizeof(ALL_AUGS) / sizeof(ALL_AUGS[0])) == AUG_TOTAL,
              "Augment catalog entry count changed; update AUG_TOTAL deliberately.");
